import { Josefin_Sans } from 'next/font/google';
import "./globals.css";
import ChildCom from "./ChildCom";

const roboto = Josefin_Sans({
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <ChildCom children={children}/>
      </body>
    </html>
  );
}
